export type ColorType = {
  name: string;
  displayName: string;
  description: string;
  cssVariable: string;
  example: string;
  usage: string;
  contrast?: string[];
  value: string;
  type: "main" | "supporting";
  dontAccountForDirection?: boolean; // For colors like primary, light -> dark or dark -> light don't matter and raw adjustment should
  reference?: string;
  adjustment?: [number, number, number]; // hsl
};

type Colors = [
  "base",
  "base-focus",
  "base-2",
  "base-2-focus",
  "base-content",
  "base-content-2",
  "base-content-3",
  "overlay",
  "overlay-focus",
  "overlay-2",
  "overlay-2-focus",
  "overlay-content",
  "overlay-content-2",
  "overlay-content-3",
  "input",
  "input-focus",
  "input-content",
  "input-content-2",
  "line",
  "line-focus",
  "primary",
  "primary-focus",
  "primary-content",
  "primary-subtle",
  "primary-subtle-content",
  "secondary",
  "secondary-focus",
  "secondary-content",
  "secondary-subtle",
  "secondary-subtle-content",
  "info",
  "info-focus",
  "info-content",
  "info-subtle",
  "info-subtle-content",
  "success",
  "success-focus",
  "success-content",
  "success-subtle",
  "success-subtle-content",
  "danger",
  "danger-focus",
  "danger-content",
  "danger-subtle",
  "danger-subtle-content",
  "warning",
  "warning-focus",
  "warning-content",
  "warning-subtle",
  "warning-subtle-content"
][number];

export type ColorsType = {
  [C in Colors]: ColorType;
};

export const colors = {
  base: {
    name: "base",
    displayName: "base",
    description:
      "baseはメインの背景色です。輝度90以上、20未満の色を使用することが推奨されています。",
    cssVariable: "--base",
    example: "bg-base",
    usage: "bg-base",
    contrast: ["base-content", "base-content-2", "base-content-3"],
    value: "hsl(240, 7%, 11%)",
    type: "main",
  },
  "base-focus": {
    name: "base-focus",
    displayName: "base-focus",
    description:
      "base-focus は、base background を使用する要素にフォーカス/ホバー状態を提供するために使用します。",
    cssVariable: "--base-focus",
    example: "bg-base-focus",
    usage: "bg-base-focus",
    contrast: ["base-content", "base-content-2", "base-content-focus"],
    value: "hsl(240, 7%, 28.6%)",
    type: "supporting",
    reference: "base",
    adjustment: [0, 0, 16],
  },
  "base-2": {
    name: "base-2",
    displayName: "base-2",
    description:
      "base-2は、カードやセクションのように、baseの上に別のレイヤーを用意するために使用されます。高さ/奥行きを出すために使用します。",
    cssVariable: "--base-2",
    example: "bg-base-2",
    usage: "bg-base-2",
    contrast: ["base-content", "base-content-2", "base-content-3"],
    value: "hsl(240, 7%, 15.4%)",
    type: "supporting",
    reference: "base",
    adjustment: [0, 0, 4],
  },
  "base-2-focus": {
    name: "base-2-focus",
    displayName: "base-2-focus",
    description:
      "base-2-focus は、base background を使用する要素にフォーカス/ホバー状態を提供するために使用します。",
    cssVariable: "--base-2-focus",
    example: "bg-base-2-focus",
    usage: "bg-base-2-focus",
    contrast: ["base-content", "base-content-2", "base-content-focus"],
    value: "hsl(240, 7%, 19.8%)",
    type: "supporting",
    reference: "base-2",
    adjustment: [0, 0, 4],
  },
  "base-content": {
    name: "base-content",
    displayName: "base-content / base-content",
    description:
      "ベースの上に使用されるメインテキストの色です。あなたのサイトで最もよく使われる色です。",
    cssVariable: "--base-content",
    example: "bg-base-content",
    usage: "bg-base-content",
    contrast: ["base", "base-2", "base-3"],
    value: "hsl(240, 7%, 100%)",
    type: "supporting",
    reference: "base",
    adjustment: [0, 0, 88],
  },
  "base-content-2": {
    name: "base-content-2",
    displayName: "base-content-2",
    description:
      "通常、ヘッダーやラベルなど、ベースコンテンツとのコントラストを出すために使用するテキストカラー。",
    cssVariable: "--base-content-2",
    example: "bg-base-content-2",
    usage: "bg-base-content-2",
    contrast: ["base", "base-2", "base-3"],
    value: "hsl(240, 7%, 90%)",
    adjustment: [0, 0, 10],
    type: "supporting",
    reference: "base-content",
  },
  "base-content-3": {
    name: "base-content-3",
    displayName: "base-content-3",
    description:
      "ベースコンテンツと2とのコントラストをつけるために使用されるテキストカラーで、通常、小さなディテールに使用される。ほとんど使用しないほうがよい。",
    cssVariable: "--base-content-3",
    example: "bg-base-content-3",
    usage: "bg-base-content-3",
    contrast: ["base", "base-2", "base-3"],
    value: "hsl(240, 7%, 70%)",
    adjustment: [0, 0, 30],
    type: "supporting",
    reference: "base-content",
  },
  overlay: {
    name: "overlay",
    displayName: "overlay / overlay",
    description:
      "メインのオーバーレイの色です。モーダル、ポップオーバー、メニューに使用します。前景にあるすべてのもの。",
    cssVariable: "--overlay",
    example: "bg-overlay",
    usage: "bg-overlay",
    contrast: ["overlay-content", "overlay-content-2", "overlay-content-3"],
    value: "hsl(240, 7%, 18.7%)",
    type: "supporting",
    reference: "base",
    adjustment: [0, 0, 7],
  },
  "overlay-focus": {
    name: "overlay-focus",
    displayName: "overlay-focus",
    description: "フォーカス/ホバー状態に使用されるオーバーレイの色。",
    cssVariable: "--overlay-focus",
    example: "bg-overlay-focus",
    usage: "bg-overlay-focus",
    contrast: ["overlay-content", "overlay-content-2", "overlay-content-3"],
    value: "hsl(240, 7%, 38.5%)",
    type: "supporting",
    reference: "overlay",
    adjustment: [0, 0, 18],
  },
  "overlay-2": {
    name: "overlay-2",
    displayName: "overlay-2",
    description:
      "2番目のオーバーレイカラーです。モーダル、ポップオーバー、メニューに使用します。オーバーレイに2層目のコントラストを提供します。",
    cssVariable: "--overlay-2",
    example: "bg-overlay-2",
    usage: "bg-overlay-2",
    contrast: ["overlay-content", "overlay-content-2", "overlay-content-3"],
    value: "hsl(240, 7%, 26.4%)",
    type: "supporting",
    reference: "overlay",
    adjustment: [0, 0, 7],
  },
  "overlay-2-focus": {
    name: "overlay-2-focus",
    displayName: "overlay-2-focus",
    description:
      "オーバーレイ2のフォーカス/ホバー状態に使用されるオーバーレイカラー。",
    cssVariable: "--overlay-2-focus",
    example: "bg-overlay-2-focus",
    usage: "bg-overlay-2-focus",
    contrast: ["overlay-content", "overlay-content-2", "overlay-content-3"],
    value: "hsl(240, 7%, 38.5%)",
    type: "supporting",
    reference: "overlay",
    adjustment: [0, 0, 18],
  },
  "overlay-content": {
    name: "overlay-content",
    displayName: "overlay-content / overlay-content",
    description:
      "メインのオーバーレイのテキスト色です。オーバーレイの中で最も目立つ色です。",
    cssVariable: "--overlay-content",
    example: "bg-overlay-content",
    usage: "text-overlay-content",
    contrast: ["overlay", "overlay-2", "overlay-3"],
    value: "hsl(240, 7%, 100%)",
    type: "supporting",
    reference: "base",
    adjustment: [0, 0, 88],
  },
  "overlay-content-2": {
    name: "overlay-content-2",
    displayName: "overlay-content-2",
    description:
      "2番目のオーバーレイの文字色です。オーバーレイで2番目に目立つ色です。ラベルによく使われます。",
    cssVariable: "--overlay-content-2",
    example: "bg-overlay-content-2",
    usage: "text-overlay-content-2",
    contrast: ["overlay", "overlay-2", "overlay-3"],
    value: "hsl(240, 7%, 90%)",
    type: "supporting",
    reference: "overlay-content",
    adjustment: [0, 0, 10],
  },
  "overlay-content-3": {
    name: "overlay-content-3",
    displayName: "overlay-content-3",
    description:
      "3番目のオーバーレイの文字色です。非常に小さな詳細や、コンテンツやコンテンツ-2から視覚的に区別する必要がある重要度の低い情報に使用します。",
    cssVariable: "--overlay-content-3",
    example: "bg-overlay-content-3",
    usage: "text-overlay-content-3",
    contrast: ["overlay", "overlay-2", "overlay-3"],
    value: "hsl(240, 7%, 80%)",
    type: "supporting",
    reference: "overlay-content",
    adjustment: [0, 0, 20],
  },
  line: {
    name: "line",
    displayName: "line",
    description: "ボーダーや仕切りなど、細い線に使用します。",
    cssVariable: "--line",
    example: "bg-line",
    usage: "divide-y-line",
    contrast: [],
    value: "hsl(240, 7%, 2.2%)",
    type: "supporting",
    reference: "base",
    adjustment: [5, 10, -8],
    dontAccountForDirection: true,
  },
  "line-focus": {
    name: "line-focus",
    displayName: "line-focus",
    description:
      "フォーカス/ホバー状態でのボーダー、仕切り、その他細い線に使用します。",
    cssVariable: "--line-focus",
    example: "bg-line-focus",
    usage: "divide-y-line-focus",
    contrast: [],
    value: "hsl(240, 7%, 18.7%)",
    type: "supporting",
    reference: "line",
    adjustment: [0, 0, 15],
  },
  input: {
    name: "input",
    displayName: "input",
    description: "input要素のメインとなる背景色です。",
    cssVariable: "--input",
    example: "bg-input",
    usage: "bg-input",
    contrast: ["input-content"],
    value: "hsl(240, 7%, 14.3%)",
    type: "supporting",
    reference: "base",
    adjustment: [5, 10, 3],
    dontAccountForDirection: true,
  },
  "input-focus": {
    name: "input-focus",
    displayName: "input-focus",
    description: "フォーカス/ホバー状態にある入力の背景色です。",
    cssVariable: "--input-focus",
    example: "hover:bg-input-focus",
    usage: "bg-input-focus",
    contrast: ["input-content"],
    value: "hsl(240, 7%, 14.3%)",
    type: "supporting",
    reference: "base",
    adjustment: [5, 10, 3],
    dontAccountForDirection: true,
  },
  "input-content": {
    name: "input-content",
    displayName: "input-content",
    description: "入力内容の色。入力値に使用される。",
    cssVariable: "--input-content",
    example: "bg-input-content",
    usage: "bg-input-content",
    contrast: ["input"],
    value: "hsl(240, 7%, 100%)",
    type: "supporting",
    reference: "input",
    adjustment: [0, 0, 85],
  },
  "input-content-2": {
    name: "input-content-2",
    displayName: "input-content-2",
    description: "第二の入力内容の色。一般にプレースホルダに使用される。",
    cssVariable: "--input-content-2",
    example: "bg-input-content-2",
    usage: "bg-input-content-2",
    contrast: ["input"],
    type: "supporting",
    value: "hsl(240, 7%, 80%)",
    reference: "input-content",
    adjustment: [0, 0, 20],
  },
  primary: {
    name: "primary",
    displayName: "primary",
    description:
      "ボタンやリンクなどに使用されるプライマーカラー。これは、ほとんどの場合、あなたのメインのブランドカラーです。背景、ボーダー、テキストに使用することができます。",
    cssVariable: "--primary",
    example: "bg-primary",
    usage: "bg-primary",
    contrast: ["primary-content"],
    value: "hsl(41, 100%, 51%)",
    type: "main",
  },
  "primary-focus": {
    name: "primary-focus",
    displayName: "primary-focus",
    description: "プライマリー用のフォーカス/ホバー状態。",
    cssVariable: "--primary-focus",
    example: "bg-primary-focus",
    usage: "bg-primary-focus",
    contrast: ["primary-content"],
    value: "hsl(41, 100%, 45.5%)",
    type: "supporting",
    reference: "primary",
    adjustment: [0, 10, -5],
    dontAccountForDirection: true,
  },
  "primary-subtle": {
    name: "primary-subtle",
    displayName: "primary-subtle",
    description:
      "微妙なプライマリー。背景、ボーダー、テキストなどに使用される。テーマの明暗に関係なく、常にプライマリーより明るい色です。",
    cssVariable: "--primary-subtle",
    example: "bg-primary-subtle",
    usage: "bg-primary-subtle",
    contrast: ["primary-content"],
    value: "hsl(41, 100%, 78.5%)",
    adjustment: [0, 10, 25],
    type: "supporting",
    reference: "primary",
    dontAccountForDirection: true,
  },
  "primary-content": {
    name: "primary-content",
    displayName: "primary-content",
    description: "bg-primary上のコンテンツのテキスト色。",
    cssVariable: "--primary-content",
    example: "bg-primary-content",
    usage: "bg-primary-content",
    contrast: ["primary"],
    value: "hsl(41, 100%, 0%)",
    type: "supporting",
    reference: "primary",
    adjustment: [0, 10, 95],
  },
  "primary-subtle-content": {
    name: "primary-subtle-content",
    displayName: "primary-subtle-content",
    description: "bg-primary-subtle のコンテンツに使用します。",
    cssVariable: "--primary-subtle-content",
    example: "bg-primary-subtle-content",
    usage: "text-primary-subtle-content",
    contrast: ["primary-content"],
    value: "hsl(41, 100%, 0%)",
    type: "supporting",
    reference: "primary-subtle",
    adjustment: [0, 10, 95],
  },
  secondary: {
    name: "secondary",
    displayName: "secondary",
    description: "セカンダリカラーです。ボタンやリンクなどに使用します。",
    cssVariable: "--secondary",
    example: "bg-secondary",
    usage: "bg-secondary",
    contrast: ["secondary-content"],
    value: "hsl(200, 97%, 41%)",
    type: "main",
  },
  "secondary-focus": {
    name: "secondary-focus",
    displayName: "secondary-focus",
    description: "フォーカス/ホバー状態でのセカンダリカラー。",
    cssVariable: "--secondary-focus",
    example: "bg-secondary-focus",
    usage: "bg-secondary-focus",
    contrast: ["secondary-content"],
    value: "hsl(200, 97%, 35.5%)",
    reference: "secondary",
    adjustment: [0, 10, -5],
    dontAccountForDirection: true,
    type: "supporting",
  },
  "secondary-subtle": {
    name: "secondary-subtle",
    displayName: "secondary-subtle",
    description:
      "微妙な副色。背景、ボーダー、テキストなどに使用します。テーマの明暗に関係なく、常にsecondaryより明るい色になります。",
    cssVariable: "--secondary-subtle",
    example: "bg-secondary-subtle",
    usage: "bg-secondary-subtle",
    contrast: ["secondary-content"],
    value: "hsl(200, 97%, 68.5%)",
    adjustment: [0, 10, 25],
    type: "supporting",
    reference: "secondary",
    dontAccountForDirection: true,
  },
  "secondary-subtle-content": {
    name: "secondary-subtle-content",
    displayName: "secondary-subtle-content",
    description: "bg-secondary-subtleのコンテンツに使用します。",
    cssVariable: "--secondary-subtle-content",
    example: "bg-secondary-subtle-content",
    usage: "text-secondary-subtle-content",
    contrast: ["secondary-content"],
    value: "hsl(200, 97%, 0%)",
    type: "supporting",
    reference: "secondary-subtle",
    adjustment: [0, 10, 95],
  },
  "secondary-content": {
    name: "secondary-content",
    displayName: "secondary-content",
    description: "bg-secondary上のコンテンツのテキスト色。",
    cssVariable: "--secondary-content",
    example: "bg-secondary-content",
    usage: "bg-secondary-content",
    contrast: ["secondary"],
    value: "hsl(200, 97%, 100%)",
    type: "supporting",
    reference: "secondary",
    adjustment: [0, 10, 95],
  },
  info: {
    name: "info",
    displayName: "info",
    description:
      "インフォカラーです。アラート、バッジなどに使用される。通常、青の濃淡がある。",
    cssVariable: "--info",
    example: "bg-info",
    usage: "bg-info",
    contrast: ["info-content"],
    value: "hsl(212, 50%, 40%)",
    type: "main",
  },
  "info-focus": {
    name: "info-focus",
    displayName: "info-focus",
    description:
      "フォーカス/ホバー状態での情報色。通常、青色の濃淡で、infoよりも暗い。",
    cssVariable: "--info-focus",
    example: "bg-info-focus",
    usage: "bg-info-focus",
    contrast: ["info-content"],
    value: "hsl(212, 50%, 34.5%)",
    type: "supporting",
    reference: "info",
    adjustment: [0, 10, -5],
    dontAccountForDirection: true,
  },
  "info-subtle": {
    name: "info-subtle",
    displayName: "info-subtle",
    description:
      "微妙なインフォカラー。背景、ボーダー、テキストに使用される。通常、青の色調で、テーマの明暗にかかわらず、常に情報より明るい。",
    cssVariable: "--info-subtle",
    example: "bg-info-subtle",
    usage: "bg-info-subtle",
    contrast: ["info-content"],
    value: "hsl(212, 50%, 67.5%)",
    adjustment: [0, 10, 25],
    type: "supporting",
    reference: "info",
  },
  "info-subtle-content": {
    name: "info-subtle-content",
    displayName: "info-subtle-content",
    description: "bg-info-subtleのコンテンツに使用します。",
    cssVariable: "--info-subtle-content",
    example: "bg-info-subtle-content",
    usage: "text-info-subtle-content",
    contrast: ["info-content"],
    value: "hsl(212, 50%, 0%)",
    type: "supporting",
    reference: "info-subtle",
    adjustment: [0, 10, 95],
  },
  "info-content": {
    name: "info-content",
    displayName: "info-content",
    description: "bg-infoのコンテンツの文字色。",
    cssVariable: "--info-content",
    example: "bg-info-content",
    usage: "bg-info-content",
    contrast: ["info"],
    value: "hsl(212, 50%, 100%)",
    type: "supporting",
    reference: "info",
    adjustment: [0, 10, 95],
  },
  danger: {
    name: "danger",
    displayName: "danger",
    description:
      "危険色です。アラート、バッジ、エラーなどに使用される。通常、赤の色合い。",
    cssVariable: "--danger",
    example: "bg-danger",
    usage: "bg-danger",
    contrast: ["danger-content"],
    value: "hsl(0, 75%, 42%)",
    type: "main",
  },
  "danger-focus": {
    name: "danger-focus",
    displayName: "danger-focus",
    description:
      "フォーカス/ホバー状態での危険色。通常は赤の色合いで、dangerより暗い色です。",
    cssVariable: "--danger-focus",
    example: "bg-danger-focus",
    usage: "bg-danger-focus",
    contrast: ["danger-content"],
    value: "hsl(0, 75%, 36.5%)",
    type: "supporting",
    reference: "danger",
    adjustment: [0, 10, -5],
    dontAccountForDirection: true,
  },
  "danger-subtle": {
    name: "danger-subtle",
    displayName: "danger-subtle",
    description:
      "さりげない危険色。背景、ボーダー、テキストなどに使用される。通常、赤の色合いで、テーマの明暗に関係なく、常にdangerより明るい。",
    cssVariable: "--danger-subtle",
    example: "bg-danger-subtle",
    usage: "bg-danger-subtle",
    contrast: ["danger-content"],
    value: "hsl(0, 75%, 69.5%)",
    type: "supporting",
    adjustment: [0, 10, 25],
    reference: "danger",
  },
  "danger-subtle-content": {
    name: "danger-subtle-content",
    displayName: "danger-subtle-content",
    description: "bg-danger-subtleのコンテンツに使用されています。",
    cssVariable: "--danger-subtle-content",
    example: "bg-danger-subtle-content",
    usage: "text-danger-subtle-content",
    contrast: ["danger-content"],
    value: "hsl(0, 75%, 0%)",
    type: "supporting",
    reference: "danger-subtle",
    adjustment: [0, 10, 95],
  },
  "danger-content": {
    name: "danger-content",
    displayName: "danger-content",
    description: "bg-dangerのコンテンツの文字色です。",
    cssVariable: "--danger-content",
    example: "bg-danger-content",
    usage: "bg-danger-content",
    contrast: ["danger"],
    value: "hsl(0, 75%, 100%)",
    type: "supporting",
    adjustment: [0, 10, 95],
    reference: "danger",
  },
  success: {
    name: "success",
    displayName: "success",
    description:
      "サクセスカラーです。アラート、バッジなどに使用される。通常、緑色の濃淡があります。",
    cssVariable: "--success",
    example: "bg-success",
    usage: "bg-success",
    contrast: ["success-content"],
    value: "hsl(159, 61%, 41%)",
    type: "main",
  },
  "success-focus": {
    name: "success-focus",
    displayName: "success-focus",
    description:
      "フォーカス/ホバー状態でのサクセスカラー。通常は緑色の濃淡で、successより暗い。",
    cssVariable: "--success-focus",
    example: "bg-success-focus",
    usage: "bg-success-focus",
    contrast: ["success-content"],
    value: "hsl(159, 61%, 35.5%)",
    type: "supporting",
    reference: "success",
    adjustment: [0, 10, -5],
    dontAccountForDirection: true,
  },
  "success-subtle": {
    name: "success-subtle",
    displayName: "success-subtle",
    description:
      "さりげないサクセスカラー。背景、ボーダー、テキストに使用される。通常は緑色の濃淡で、テーマの明暗に関係なく、常にsuccessより明るい。",
    cssVariable: "--success-subtle",
    example: "bg-success-subtle",
    usage: "bg-success-subtle",
    contrast: ["success-content"],
    value: "hsl(159, 61%, 16%)",
    adjustment: [0, 10, 25],
    type: "supporting",
    reference: "success",
  },
  "success-subtle-content": {
    name: "success-subtle-content",
    displayName: "success-subtle-content",
    description: "bg-success-subtleのコンテンツに使用されています。",
    cssVariable: "--success-subtle-content",
    example: "bg-success-subtle-content",
    usage: "text-success-subtle-content",
    contrast: ["success-content"],
    value: "hsl(159, 61%, 100%)",
    type: "supporting",
    reference: "success-subtle",
    adjustment: [0, 10, 95],
  },
  "success-content": {
    name: "success-content",
    displayName: "success-content",
    description: "bg-successのコンテンツの文字色です。",
    cssVariable: "--success-content",
    example: "bg-success-content",
    usage: "bg-success-content",
    contrast: ["success"],
    value: "hsl(159, 61%, 0%)",
    adjustment: [0, 10, 95],
    type: "supporting",
    reference: "success",
  },
  warning: {
    name: "warning",
    displayName: "warning",
    description:
      "警告色です。注意喚起やバッジなどに使用される。通常、黄色の濃淡がある。",
    cssVariable: "--warning",
    example: "bg-warning",
    usage: "bg-warning",
    contrast: ["warning-content"],
    value: "hsl(49, 95%, 53%)",
    type: "main",
  },
  "warning-focus": {
    name: "warning-focus",
    displayName: "warning-focus",
    description:
      "フォーカス/ホバー状態での警告色。通常は黄色に近い色合いで、warningより濃い色です。",
    cssVariable: "--warning-focus",
    example: "bg-warning-focus",
    usage: "bg-warning-focus",
    contrast: ["warning-content"],
    value: "hsl(49, 95%, 47.5%)",
    type: "supporting",
    reference: "warning",
    adjustment: [0, 10, -5],
    dontAccountForDirection: true,
  },
  "warning-subtle": {
    name: "warning-subtle",
    displayName: "warning-subtle",
    description:
      "微妙な警告色。背景、ボーダー、テキストに使用される。通常は黄色の濃淡で、テーマの明暗にかかわらず、常にwarningより明るい色です。",
    cssVariable: "--warning-subtle",
    example: "bg-warning-subtle",
    usage: "bg-warning-subtle",
    contrast: ["warning-content"],
    value: "hsl(49, 95%, 28%)",
    adjustment: [0, 10, 25],
    type: "supporting",
    reference: "warning",
  },
  "warning-subtle-content": {
    name: "warning-subtle-content",
    displayName: "warning-subtle-content",
    description: "bg-warning-subtleのコンテンツに使用します。",
    cssVariable: "--warning-subtle-content",
    example: "bg-warning-subtle-content",
    usage: "text-warning-subtle-content",
    contrast: ["warning-content"],
    value: "hsl(49, 95%, 100%)",
    type: "supporting",
    reference: "warning-subtle",
    adjustment: [0, 10, 95],
  },
  "warning-content": {
    name: "warning-content",
    displayName: "warning-content",
    description: "警告内容に使われる色です。",
    cssVariable: "--warning-content",
    example: "bg-warning-content",
    usage: "bg-warning-content",
    contrast: ["warning"],
    value: "hsl(49, 95%, 0%)",
    adjustment: [0, 10, 95],
    type: "supporting",
    reference: "warning",
  },
} satisfies ColorsType;
