name: Setup
description: Setup Node.js and restore packages

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.6
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-store
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      name: Setup pnpm cache
      id: pnpm-cache
      with:
        path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: |
        if ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}; then
         pnpm install
        fi
